package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonAutoDetect;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,schema="public"
)
@JsonAutoDetect
public class Account  implements java.io.Serializable {


     private int id;
     private String fullName;
     private String address;
     private Date birthday;
     private Boolean gender;
     private String avatar;
     private String visaCode;
     private Set<User> users = new HashSet<User>(0);

    public Account() {
    }

	
    public Account(int id) {
        this.id = id;
    }
    public Account(int id, String fullName, String address, Date birthday, Boolean gender, String avatar, String visaCode, Set<User> users) {
       this.id = id;
       this.fullName = fullName;
       this.address = address;
       this.birthday = birthday;
       this.gender = gender;
       this.avatar = avatar;
       this.visaCode = visaCode;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="full_name")
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=13)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="gender")
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    
    @Column(name="avatar")
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    
    @Column(name="visa_code")
    public String getVisaCode() {
        return this.visaCode;
    }
    
    public void setVisaCode(String visaCode) {
        this.visaCode = visaCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


