package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonAutoDetect;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BillDetail generated by hbm2java
 */
@Entity
@Table(name="bill_detail"
    ,schema="public"
)
@JsonAutoDetect
public class BillDetail  implements java.io.Serializable {


     private int id;
     private Product product;
     private UserBill userBill;
     private Integer amount;
     private Double totalPrice;

    public BillDetail() {
    }

	
    public BillDetail(int id) {
        this.id = id;
    }
    public BillDetail(int id, Product product, UserBill userBill, Integer amount, Double totalPrice) {
       this.id = id;
       this.product = product;
       this.userBill = userBill;
       this.amount = amount;
       this.totalPrice = totalPrice;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_product")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_bill")
    public UserBill getUserBill() {
        return this.userBill;
    }
    
    public void setUserBill(UserBill userBill) {
        this.userBill = userBill;
    }

    
    @Column(name="amount")
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    
    @Column(name="total_price", precision=17, scale=17)
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }




}


