package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ColorCategory generated by hbm2java
 */
@Entity
@Table(name = "color_category", schema = "public"
)
@JsonAutoDetect
public class ColorCategory implements java.io.Serializable {

    private int id;
    private String value;
    private Set<ProductColorDetail> productColorDetails = new HashSet<ProductColorDetail>(0);

    public ColorCategory() {
    }

    public ColorCategory(int id) {
        this.id = id;
    }

    public ColorCategory(int id, String value, Set<ProductColorDetail> productColorDetails) {
        this.id = id;
        this.value = value;
        this.productColorDetails = productColorDetails;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "value")
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "colorCategory")
    @JsonBackReference
    public Set<ProductColorDetail> getProductColorDetails() {
        return this.productColorDetails;
    }

    public void setProductColorDetails(Set<ProductColorDetail> productColorDetails) {
        this.productColorDetails = productColorDetails;
    }

}
