package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonBackReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductDetail generated by hbm2java
 */
@Entity
@Table(name = "product_detail", schema = "public"
)
@JsonAutoDetect
public class ProductDetail implements java.io.Serializable {

    private int id;
    private ProducerCategory producerCategory;
    private Product product;
    private Double screenSize;
    private Integer ram;
    private Integer capacityPin;
    private Integer simAmount;
    private String screen;
    private String cpu;
    private Double weight;
    private Double usb;
    private String bluetooth;
    private Double mainCamera;
    private Double viceCamera;
    private String gpu;
    private Integer guarantee;

    public ProductDetail() {
    }

    public ProductDetail(int id) {
        this.id = id;
    }

    public ProductDetail(int id, ProducerCategory producerCategory, Product product, Double screenSize, Integer ram, Integer capacityPin, Integer simAmount, String screen, String cpu, Double weight, Double usb, String bluetooth, Double mainCamera, Double viceCamera, String gpu, Integer guarantee) {
        this.id = id;
        this.producerCategory = producerCategory;
        this.product = product;
        this.screenSize = screenSize;
        this.ram = ram;
        this.capacityPin = capacityPin;
        this.simAmount = simAmount;
        this.screen = screen;
        this.cpu = cpu;
        this.weight = weight;
        this.usb = usb;
        this.bluetooth = bluetooth;
        this.mainCamera = mainCamera;
        this.viceCamera = viceCamera;
        this.gpu = gpu;
        this.guarantee = guarantee;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_producer")
    @JsonBackReference
    public ProducerCategory getProducerCategory() {
        return this.producerCategory;
    }

    public void setProducerCategory(ProducerCategory producerCategory) {
        this.producerCategory = producerCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_product")
    @JsonBackReference
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @Column(name = "screen_size", precision = 17, scale = 17)
    public Double getScreenSize() {
        return this.screenSize;
    }

    public void setScreenSize(Double screenSize) {
        this.screenSize = screenSize;
    }

    @Column(name = "ram")
    public Integer getRam() {
        return this.ram;
    }

    public void setRam(Integer ram) {
        this.ram = ram;
    }

    @Column(name = "capacity_pin")
    public Integer getCapacityPin() {
        return this.capacityPin;
    }

    public void setCapacityPin(Integer capacityPin) {
        this.capacityPin = capacityPin;
    }

    @Column(name = "sim_amount")
    public Integer getSimAmount() {
        return this.simAmount;
    }

    public void setSimAmount(Integer simAmount) {
        this.simAmount = simAmount;
    }

    @Column(name = "screen")
    public String getScreen() {
        return this.screen;
    }

    public void setScreen(String screen) {
        this.screen = screen;
    }

    @Column(name = "cpu")
    public String getCpu() {
        return this.cpu;
    }

    public void setCpu(String cpu) {
        this.cpu = cpu;
    }

    @Column(name = "weight", precision = 17, scale = 17)
    public Double getWeight() {
        return this.weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    @Column(name = "usb", precision = 17, scale = 17)
    public Double getUsb() {
        return this.usb;
    }

    public void setUsb(Double usb) {
        this.usb = usb;
    }

    @Column(name = "bluetooth")
    public String getBluetooth() {
        return this.bluetooth;
    }

    public void setBluetooth(String bluetooth) {
        this.bluetooth = bluetooth;
    }

    @Column(name = "main_camera", precision = 17, scale = 17)
    public Double getMainCamera() {
        return this.mainCamera;
    }

    public void setMainCamera(Double mainCamera) {
        this.mainCamera = mainCamera;
    }

    @Column(name = "vice_camera", precision = 17, scale = 17)
    public Double getViceCamera() {
        return this.viceCamera;
    }

    public void setViceCamera(Double viceCamera) {
        this.viceCamera = viceCamera;
    }

    @Column(name = "gpu")
    public String getGpu() {
        return this.gpu;
    }

    public void setGpu(String gpu) {
        this.gpu = gpu;
    }

    @Column(name = "guarantee")
    public Integer getGuarantee() {
        return this.guarantee;
    }

    public void setGuarantee(Integer guarantee) {
        this.guarantee = guarantee;
    }

}
