package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonBackReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductColorDetail generated by hbm2java
 */
@Entity
@Table(name = "product_color_detail", schema = "public"
)
@JsonAutoDetect
public class ProductColorDetail implements java.io.Serializable {

    private int id;
    private ColorCategory colorCategory;
    private Product product;

    public ProductColorDetail() {
    }

    public ProductColorDetail(int id) {
        this.id = id;
    }

    public ProductColorDetail(int id, ColorCategory colorCategory, Product product) {
        this.id = id;
        this.colorCategory = colorCategory;
        this.product = product;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_color")
    @JsonBackReference
    public ColorCategory getColorCategory() {
        return this.colorCategory;
    }

    public void setColorCategory(ColorCategory colorCategory) {
        this.colorCategory = colorCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_product")
    @JsonBackReference
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

}
