package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProducerCategory generated by hbm2java
 */
@Entity
@Table(name = "producer_category", schema = "public"
)
@JsonAutoDetect
public class ProducerCategory implements java.io.Serializable {

    private int id;
    private String value;
    private Set<ProductDetail> productDetails = new HashSet<ProductDetail>(0);

    public ProducerCategory() {
    }

    public ProducerCategory(int id, String value) {
        this.id = id;
        this.value = value;
    }

    public ProducerCategory(int id, String value, Set<ProductDetail> productDetails) {
        this.id = id;
        this.value = value;
        this.productDetails = productDetails;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "value", nullable = false)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "producerCategory")
    @JsonBackReference
    public Set<ProductDetail> getProductDetails() {
        return this.productDetails;
    }

    public void setProductDetails(Set<ProductDetail> productDetails) {
        this.productDetails = productDetails;
    }

}
