package turbo.POJO;
// Generated Dec 16, 2015 11:33:51 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public"
)
public class Product implements java.io.Serializable {

    private int id;
    
    private String code;
    private String image;
    private Double price;
    private Integer amount;
    private String name;
    private Set<ProductColorDetail> productColorDetails = new HashSet<ProductColorDetail>(0);
    private Set<ProductDetail> productDetails = new HashSet<ProductDetail>(0);
    private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

    public Product() {
    }

    public Product(int id) {
        this.id = id;
    }

    public Product(int id, String code, String image, Double price, Integer amount, String name, Set<ProductColorDetail> productColorDetails, Set<ProductDetail> productDetails, Set<BillDetail> billDetails) {
        this.id = id;
        this.code = code;
        this.image = image;
        this.price = price;
        this.amount = amount;
        this.name = name;
        this.productColorDetails = productColorDetails;
        this.productDetails = productDetails;
        this.billDetails = billDetails;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "code")
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "image")
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "price", precision = 17, scale = 17)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "amount")
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
    @JsonBackReference
    public Set<ProductColorDetail> getProductColorDetails() {
        return this.productColorDetails;
    }

    public void setProductColorDetails(Set<ProductColorDetail> productColorDetails) {
        this.productColorDetails = productColorDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
    @JsonBackReference
    public Set<ProductDetail> getProductDetails() {
        return this.productDetails;
    }

    public void setProductDetails(Set<ProductDetail> productDetails) {
        this.productDetails = productDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
    @JsonBackReference
    public Set<BillDetail> getBillDetails() {
        return this.billDetails;
    }

    public void setBillDetails(Set<BillDetail> billDetails) {
        this.billDetails = billDetails;
    }

}
